name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: spack/setup-spack@bbb4eb97fe9eebb51de5f9a6b6aedbcec4f0a226
      
      - name: Run tests
        shell: spack-bash {0}
        run: |
          which spack
          echo SPACK_ROOT: $SPACK_ROOT
          . source_me.sh
          spack unit-test --extension=helpers -m "not integration"
          # Run the long-running tests after we've run the short ones:
          spack unit-test --extension=helpers -m "integration"
