name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: spack/setup-spack@v2
      
      - name: Run tests
        shell: spack-bash {0}
        run: |
          . source_me.sh
          spack unit-test --extension=helpers -m "not integration"
          # Run the long-running tests after we've run the short ones:
          spack unit-test --extension=helpers -m "integration"
